### ISSUE TITLE
possible invalid url in NHM Interactions Bank meta-data

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#266]
@edwbaker it seems that metadata for NHM Interactions Bank at http://data.nhm.ac.uk/api/3/action/package_show?id=nhm-ib contains a url with a typo:

```http://data.nhm.ac.uk//dataset/82e807f0-6273-4f19-be0a-7f7558442a25/resource/1f64e2cf-d738-4a7c-9e81-a1951eac635f/download/output.csv```

notice the double ``//``. 

Please confirm that the double ```//``` is a typo.

**Comment by edwbaker** [comment]
Related to NaturalHistoryMuseum/ckanext-nhm#325

**Comment by edwbaker** [comment]
This is a typo - and should be fixed soon.

**Comment by jhpoelen** [comment]
@edwbaker @benscott  Just confirmed that the typo was corrected. Thanks!

**Comment by jhpoelen** [comment]
Oops. I take that back: the typo still exists. I relied on my ability to visually parse json . . . I re-ran the tests to confirm that the issue is still present. Sorry about the confusion.

**Comment by jhpoelen** [comment]
Duplicate of https://github.com/NaturalHistoryMuseum/ckanext-nhm/issues/325 .
